# GitHub Labels Configuration for NestJS Telescope

# Bug labels
- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "critical"
  color: "d73a4a"
  description: "Critical bug that needs immediate attention"

- name: "security"
  color: "d73a4a"
  description: "Security vulnerability"

# Feature labels
- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"

- name: "feature"
  color: "a2eeef"
  description: "New functionality"

- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

# Documentation labels
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "docs"
  color: "0075ca"
  description: "Documentation updates"

# Help labels
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "question"
  color: "d876e3"
  description: "Further information is requested"

# Status labels
- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"

- name: "triage"
  color: "fef2c0"
  description: "Needs review and categorization"

# Priority labels
- name: "high priority"
  color: "d73a4a"
  description: "High priority issue"

- name: "low priority"
  color: "0e8a16"
  description: "Low priority issue"

# Type labels
- name: "ui"
  color: "fbca04"
  description: "UI/UX related changes"

- name: "api"
  color: "fbca04"
  description: "API related changes"

- name: "core"
  color: "fbca04"
  description: "Core functionality changes"

- name: "performance"
  color: "fbca04"
  description: "Performance improvements"

- name: "refactor"
  color: "fbca04"
  description: "Code refactoring"

# Testing labels
- name: "test"
  color: "c2e0c6"
  description: "Testing related changes"

- name: "coverage"
  color: "c2e0c6"
  description: "Test coverage improvements"

# Release labels
- name: "release"
  color: "5319e7"
  description: "Release related"

- name: "breaking"
  color: "d73a4a"
  description: "Breaking changes"

# Maintenance labels
- name: "maintenance"
  color: "fbca04"
  description: "Maintenance tasks"

- name: "dependencies"
  color: "0366d6"
  description: "Dependency updates"

- name: "ci/cd"
  color: "0366d6"
  description: "CI/CD related changes" 