name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## What's Changed
            
            This release includes:
            - Bug fixes and improvements
            - Performance optimizations
            - Documentation updates
            
            ## Installation
            
            ```bash
            npm install nestjs-telescope
            ```
            
            ## Usage
            
            ```typescript
            import { TelescopeModule } from 'nestjs-telescope';
            
            @Module({
              imports: [TelescopeModule],
            })
            export class AppModule {}
            ```
            
            ## Links
            
            - [Documentation](https://github.com/HiGeorges/NestJs-Telescope)
            - [Issues](https://github.com/HiGeorges/NestJs-Telescope/issues)
            - [NPM Package](https://www.npmjs.com/package/nestjs-telescope)
          draft: false
          prerelease: false 