name: Setup Labels

on:
  push:
    paths:
      - '.github/labels.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install js-yaml

      - name: Create labels
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');
            
            try {
              const labels = yaml.load(fs.readFileSync('.github/labels.yml', 'utf8'));
              
              for (const label of labels) {
                try {
                  await github.rest.issues.createLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: label.name,
                    color: label.color,
                    description: label.description
                  });
                  console.log(`✅ Created label: ${label.name}`);
                } catch (error) {
                  if (error.status === 422) {
                    // Label already exists, try to update it
                    try {
                      await github.rest.issues.updateLabel({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        name: label.name,
                        color: label.color,
                        description: label.description
                      });
                      console.log(`✅ Updated label: ${label.name}`);
                    } catch (updateError) {
                      console.log(`⚠️ Could not update label: ${label.name} - ${updateError.message}`);
                    }
                  } else {
                    console.log(`❌ Error creating label: ${label.name} - ${error.message}`);
                  }
                }
              }
              
              console.log('🎉 Labels setup completed!');
            } catch (error) {
              console.error('❌ Error reading labels.yml:', error.message);
              core.setFailed('Failed to setup labels');
            } 